name: rai-analysis
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyter
  - pip:
      - numpy<2
      - pandas<2.2
      - scikit-learn==1.5.2
      - matplotlib
      - seaborn
      - xgboost
      - shap
      - joblib
      - responsibleai
      - raiwidgets
      - erroranalysis
      - econml<0.16
      - interpret-community
